name: Vercel Deployment

# Trigger deployment on push to main and pull requests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run linter
      run: npm run lint
      continue-on-error: true
      
    - name: Install Vercel CLI
      run: npm install --global vercel@latest
      
    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      
    - name: Build Project Artifacts
      run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      
    - name: Deploy Project Artifacts to Vercel (Preview)
      if: github.event_name == 'pull_request'
      id: deploy-preview
      run: |
        url=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})
        echo "preview_url=$url" >> $GITHUB_OUTPUT
        
    - name: Deploy Project Artifacts to Vercel (Production)
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      id: deploy-production
      run: |
        url=$(vercel deploy --prod --prebuilt --token=${{ secrets.VERCEL_TOKEN }})
        echo "production_url=$url" >> $GITHUB_OUTPUT
        
    - name: Comment PR with Preview URL
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `🚀 **Preview Deployment Ready!**
            
            ✅ Your changes have been deployed to Vercel:
            **Preview URL:** ${{ steps.deploy-preview.outputs.preview_url }}
            
            📱 Test your changes:
            - [AI Video Studio](${{ steps.deploy-preview.outputs.preview_url }}/ai-video-studio.html)
            - [Advanced Creator](${{ steps.deploy-preview.outputs.preview_url }}/advanced-video-creator.html)
            - [Video Generator](${{ steps.deploy-preview.outputs.preview_url }}/video_generator.html)
            
            🤖 *Deployed via GitHub Actions*`
          })
          
    - name: Create deployment status
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.repos.createDeploymentStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            deployment_id: context.payload.deployment?.id || 0,
            state: 'success',
            environment_url: '${{ steps.deploy-production.outputs.production_url }}',
            description: 'Deployed to Vercel'
          })

  # Optional: Lighthouse performance testing
  lighthouse:
    runs-on: ubuntu-latest
    needs: deploy
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run Lighthouse CI
      uses: treosh/lighthouse-ci-action@v10
      with:
        urls: |
          ${{ needs.deploy.outputs.preview_url }}/ai-video-studio.html
        configPath: './lighthouserc.json'
        uploadArtifacts: true
        temporaryPublicStorage: true